version: '3'
services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: F2023_comp3123_assignment2

  backend:
    build:
      context: ./backend
    ports:
      - "8484:8484"
    depends_on:
      - mongodb
    environment:
      DB_CONNECTION_STRING: "mongodb+srv://admin:password@cluster0.ehf8jjp.mongodb.net/F2023_comp3123_assignment2?retryWrites=true&w=majority"

  frontend:
    build:
      context: ./frontend
    ports:
      -  "8080:80"
    depends_on:
      - backend
